"""provider ready gate: state events, turn dedup, webhook idempotency, suggestion trace_id

Revision ID: 0afc25b75166
Revises: 0cd3645f7d6d
Create Date: 2026-09-18 16:17:22.967498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afc25b75166'
down_revision: Union[str, Sequence[str], None] = '0cd3645f7d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=220), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('payload_summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_type', 'external_id', name='uq_webhook_delivery')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_provider'), ['provider'], unique=False)

    op.create_table('conversation_state_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('from_phase', sa.String(length=40), nullable=True),
    sa.Column('to_phase', sa.String(length=40), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('objection_type', sa.String(length=40), nullable=True),
    sa.Column('sales_action', sa.String(length=160), nullable=True),
    sa.Column('trigger', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_state_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_state_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_state_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_state_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_state_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_state_events_speaker'), ['speaker'], unique=False)

    op.create_table('processed_turn_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('utterance_id', sa.String(length=200), nullable=True),
    sa.Column('stream_id', sa.String(length=200), nullable=True),
    sa.Column('provider_event_id', sa.String(length=200), nullable=True),
    sa.Column('result_ref', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'action', 'turn_id', name='uq_processed_turn_event')
    )
    with op.batch_alter_table('processed_turn_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_turn_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_turn_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_turn_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_turn_events_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_turn_events_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_turn_events_utterance_id'), ['utterance_id'], unique=False)

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_suggestions_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_trace_id'))
        batch_op.drop_column('trace_id')

    with op.batch_alter_table('processed_turn_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_utterance_id'))
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_turn_id'))
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_stream_id'))
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_call_id'))
        batch_op.drop_index(batch_op.f('ix_processed_turn_events_action'))

    op.drop_table('processed_turn_events')
    with op.batch_alter_table('conversation_state_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_state_events_speaker'))
        batch_op.drop_index(batch_op.f('ix_conversation_state_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_conversation_state_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_state_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_state_events_call_id'))

    op.drop_table('conversation_state_events')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_provider'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_external_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_company_id'))

    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
