"""add conversation states

Revision ID: 0cd3645f7d6d
Revises: 11deec5ac162
Create Date: 2026-09-18 12:40:08.942004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd3645f7d6d'
down_revision: Union[str, Sequence[str], None] = '11deec5ac162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=40), nullable=False),
    sa.Column('previous_phase', sa.String(length=40), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('smalltalk_turns', sa.Integer(), nullable=False),
    sa.Column('business_transition_started', sa.Boolean(), nullable=False),
    sa.Column('opening_completed', sa.Boolean(), nullable=False),
    sa.Column('discovery_started', sa.Boolean(), nullable=False),
    sa.Column('pitch_delivered', sa.Boolean(), nullable=False),
    sa.Column('price_discussed', sa.Boolean(), nullable=False),
    sa.Column('active_objection', sa.String(length=40), nullable=True),
    sa.Column('resolved_objections', sa.JSON(), nullable=False),
    sa.Column('last_seller_action', sa.String(length=40), nullable=True),
    sa.Column('last_prospect_event', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_states_call_id'), ['call_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_states_call_id'))

    op.drop_table('conversation_states')
    # ### end Alembic commands ###
