"""call provider status for out-of-order twilio event ordering

Revision ID: 267cf4f7c8a6
Revises: 0afc25b75166
Create Date: 2026-09-18 17:19:05.329826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267cf4f7c8a6'
down_revision: Union[str, Sequence[str], None] = '0afc25b75166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_provider_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_call_id', sa.String(length=220), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('last_status', sa.String(length=40), nullable=True),
    sa.Column('last_sequence_number', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_call_id', name='uq_call_provider_status')
    )
    with op.batch_alter_table('call_provider_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_provider_status_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_provider_status_external_call_id'), ['external_call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_provider_status_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_provider_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_provider_status_provider'))
        batch_op.drop_index(batch_op.f('ix_call_provider_status_external_call_id'))
        batch_op.drop_index(batch_op.f('ix_call_provider_status_call_id'))

    op.drop_table('call_provider_status')
    # ### end Alembic commands ###
