"""turn latency trace for sprint 2 end to end timing

Revision ID: becfd144ab0b
Revises: 267cf4f7c8a6
Create Date: 2026-09-18 17:57:13.675496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becfd144ab0b'
down_revision: Union[str, Sequence[str], None] = '267cf4f7c8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_latency_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('t_audio_received_at', sa.DateTime(), nullable=True),
    sa.Column('t_asr_interim_at', sa.DateTime(), nullable=True),
    sa.Column('t_asr_final_at', sa.DateTime(), nullable=True),
    sa.Column('t_turn_end_detected_at', sa.DateTime(), nullable=True),
    sa.Column('t_salesbrain_started_at', sa.DateTime(), nullable=True),
    sa.Column('t_salesbrain_finished_at', sa.DateTime(), nullable=True),
    sa.Column('t_suggestion_persisted_at', sa.DateTime(), nullable=True),
    sa.Column('t_suggestion_pushed_at', sa.DateTime(), nullable=True),
    sa.Column('t_ui_rendered_at', sa.DateTime(), nullable=True),
    sa.Column('audio_to_interim_ms', sa.Float(), nullable=True),
    sa.Column('audio_to_final_ms', sa.Float(), nullable=True),
    sa.Column('turn_detection_latency_ms', sa.Float(), nullable=True),
    sa.Column('salesbrain_latency_ms', sa.Float(), nullable=True),
    sa.Column('suggestion_persist_latency_ms', sa.Float(), nullable=True),
    sa.Column('suggestion_push_latency_ms', sa.Float(), nullable=True),
    sa.Column('real_rsl_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_turn_id'), ['turn_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_turn_id'))
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_trace_id'))
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_created_at'))
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_company_id'))
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_call_id'))

    op.drop_table('turn_latency_traces')
    # ### end Alembic commands ###
