"""sprint 3a: render ack columns on turn latency trace

Revision ID: cc677f32642e
Revises: db72d9df9ff8
Create Date: 2026-09-18 21:23:11.360352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc677f32642e'
down_revision: Union[str, Sequence[str], None] = 'db72d9df9ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_browser_received_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('client_render_latency_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.drop_column('client_render_latency_ms')
        batch_op.drop_column('t_browser_received_at')

    # ### end Alembic commands ###
