"""monotonic runtime-id guard for server render ack latency

Revision ID: d93903408234
Revises: e30b19a3da75
Create Date: 2026-09-18 22:38:41.664752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93903408234'
down_revision: Union[str, Sequence[str], None] = 'e30b19a3da75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_turn_end_detected_monotonic_runtime_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.drop_column('t_turn_end_detected_monotonic_runtime_id')

    # ### end Alembic commands ###
