"""initial schema

Revision ID: dae87f6612b3
Revises: 
Create Date: 2026-09-18 11:51:09.648541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae87f6612b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('network_learning_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=180), nullable=False),
    sa.Column('action', sa.String(length=180), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('compliance_review_signoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=180), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=220), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_review_signoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_review_signoffs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_review_signoffs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_review_signoffs_jurisdiction'), ['jurisdiction'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('primary_metric', sa.String(length=120), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_key'), ['key'], unique=False)

    op.create_table('tenant_feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('campaign_type', sa.String(length=60), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=180), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_feature_flags_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_feature_flags_feature_key'), ['feature_key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=220), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('hired_at', sa.DateTime(), nullable=False),
    sa.Column('product_started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sellers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sellers_user_id'), ['user_id'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('prospect_company', sa.String(length=180), nullable=False),
    sa.Column('prospect_role', sa.String(length=140), nullable=False),
    sa.Column('segment', sa.String(length=140), nullable=False),
    sa.Column('offer_key', sa.String(length=120), nullable=False),
    sa.Column('campaign_key', sa.String(length=120), nullable=False),
    sa.Column('campaign_type', sa.String(length=60), nullable=False),
    sa.Column('prospect_type', sa.String(length=20), nullable=False),
    sa.Column('speaker_mode', sa.String(length=40), nullable=False),
    sa.Column('jurisdiction_country', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('consent_state', sa.String(length=40), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=80), nullable=False),
    sa.Column('meeting_booked', sa.Boolean(), nullable=False),
    sa.Column('meeting_held', sa.Boolean(), nullable=False),
    sa.Column('qualified_opportunity', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('external_call_id', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_started_at'), ['started_at'], unique=False)

    op.create_table('consent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('prospect_reference', sa.String(length=220), nullable=False),
    sa.Column('consent_type', sa.String(length=60), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('consent_text_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=60), nullable=False),
    sa.Column('evidence_ref', sa.String(length=220), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_status'), ['status'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=220), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('closed_won', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_external_id'), ['external_id'], unique=False)

    op.create_table('experiment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('variant_key', sa.String(length=80), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_assignments_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_assignments_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=220), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('held', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_starts_at'), ['starts_at'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prospect_text', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('do_not', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('language_policy', sa.JSON(), nullable=False),
    sa.Column('reaction_snapshot', sa.JSON(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_created_at'), ['created_at'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_ms', sa.Integer(), nullable=False),
    sa.Column('ended_ms', sa.Integer(), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('response_latency_ms', sa.Float(), nullable=True),
    sa.Column('pause_before_ms', sa.Float(), nullable=True),
    sa.Column('overlap_ms', sa.Float(), nullable=True),
    sa.Column('avg_loudness_dbfs', sa.Float(), nullable=True),
    sa.Column('avg_pitch_hz', sa.Float(), nullable=True),
    sa.Column('pitch_range_hz', sa.Float(), nullable=True),
    sa.Column('lexical_complexity', sa.Float(), nullable=True),
    sa.Column('style_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_speaker'), ['speaker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_speaker'))
        batch_op.drop_index(batch_op.f('ix_turns_call_id'))

    op.drop_table('turns')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_created_at'))
        batch_op.drop_index(batch_op.f('ix_suggestions_call_id'))

    op.drop_table('suggestions')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_starts_at'))
        batch_op.drop_index(batch_op.f('ix_meetings_external_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_company_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_call_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('experiment_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_assignments_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_assignments_call_id'))

    op.drop_table('experiment_assignments')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_external_id'))
        batch_op.drop_index(batch_op.f('ix_deals_company_id'))
        batch_op.drop_index(batch_op.f('ix_deals_call_id'))

    op.drop_table('deals')
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_events_status'))
        batch_op.drop_index(batch_op.f('ix_consent_events_consent_type'))
        batch_op.drop_index(batch_op.f('ix_consent_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_consent_events_captured_at'))
        batch_op.drop_index(batch_op.f('ix_consent_events_call_id'))

    op.drop_table('consent_events')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_started_at'))
        batch_op.drop_index(batch_op.f('ix_calls_seller_id'))
        batch_op.drop_index(batch_op.f('ix_calls_company_id'))

    op.drop_table('calls')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sellers_user_id'))
        batch_op.drop_index(batch_op.f('ix_sellers_company_id'))

    op.drop_table('sellers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('tenant_feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_feature_flags_feature_key'))
        batch_op.drop_index(batch_op.f('ix_tenant_feature_flags_company_id'))

    op.drop_table('tenant_feature_flags')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_key'))
        batch_op.drop_index(batch_op.f('ix_experiments_company_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('compliance_review_signoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_review_signoffs_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_compliance_review_signoffs_company_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_review_signoffs_action'))

    op.drop_table('compliance_review_signoffs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
