"""sprint 2b: real provider labeling and endpointing comparison on turn latency trace

Revision ID: db72d9df9ff8
Revises: becfd144ab0b
Create Date: 2026-09-18 18:36:13.972606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db72d9df9ff8'
down_revision: Union[str, Sequence[str], None] = 'becfd144ab0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default values below matter beyond initial backfill: they make this
    # migration safe to apply even against a table that already has rows (any
    # pre-Sprint-2B trace was necessarily produced by SimulatedASRProvider, so
    # backfilling 'simulated'/true is the honest, correct historical label, not a
    # guess) — see docs/DECISIONS.md ADR-045.
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asr_provider', sa.String(length=40), nullable=False, server_default='simulated'))
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('t_provider_endpoint_detected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('provider_endpoint_vs_turn_end_ms', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_asr_provider'), ['asr_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_latency_traces_is_synthetic'), ['is_synthetic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_is_synthetic'))
        batch_op.drop_index(batch_op.f('ix_turn_latency_traces_asr_provider'))
        batch_op.drop_column('provider_endpoint_vs_turn_end_ms')
        batch_op.drop_column('t_provider_endpoint_detected_at')
        batch_op.drop_column('is_synthetic')
        batch_op.drop_column('asr_provider')

    # ### end Alembic commands ###
