"""adr-051: rename push/rsl fields, add render-ack and clock-sync columns

Revision ID: e30b19a3da75
Revises: cc677f32642e
Create Date: 2026-09-18 22:10:23.811007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30b19a3da75'
down_revision: Union[str, Sequence[str], None] = 'cc677f32642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited from the raw autogenerated diff: `real_rsl_ms` and
    `t_suggestion_pushed_at` are RENAMES (ADR-051), not drop+add — using
    `alter_column(new_column_name=...)` here preserves any existing data instead
    of silently discarding it, which the autogenerated drop_column/add_column pair
    would have done.
    """
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.alter_column('t_suggestion_pushed_at', new_column_name='t_push_enqueued_at')
        batch_op.alter_column('real_rsl_ms', new_column_name='wallclock_rsl_estimate_ms')
        batch_op.add_column(sa.Column('t_ws_send_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('t_render_ack_received_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('t_turn_end_detected_monotonic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ws_send_latency_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('server_render_ack_latency_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_offset_estimate_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_rtt_estimate_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_uncertainty_ms', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('turn_latency_traces', schema=None) as batch_op:
        batch_op.drop_column('clock_uncertainty_ms')
        batch_op.drop_column('clock_rtt_estimate_ms')
        batch_op.drop_column('clock_offset_estimate_ms')
        batch_op.drop_column('server_render_ack_latency_ms')
        batch_op.drop_column('ws_send_latency_ms')
        batch_op.drop_column('t_turn_end_detected_monotonic')
        batch_op.drop_column('t_render_ack_received_at')
        batch_op.drop_column('t_ws_send_completed_at')
        batch_op.alter_column('wallclock_rsl_estimate_ms', new_column_name='real_rsl_ms')
        batch_op.alter_column('t_push_enqueued_at', new_column_name='t_suggestion_pushed_at')
